Mod/exercise6
PDM4AR/exercises pull request #95
Opened 2024-08-21 09:54 UTC by JoseLavariega

Main modifications:
- New task definitions for Separating Axis Theorem Exercises
- Data generation for SAT exercises 
- Modification of visualization code to take in optional arguments, if students choose to visualize the separating axis that they create. 
- Additional checker function to compare two lines, for polygon projection tasks. 
- Changes structure of ex06 (after running the checker) to include the new exercises. 
- Docstrings on all functions in collision_primitives and collision_checker, even legacy functions.

2024-08-26 15:21 UTC, alezana requested changes
@JoseLavariega @ysli16 I think you need to update the exercise instructions.
I.e., check the .md file in the docs folder

2024-08-26 15:21 UTC, alezana commented on README.md
> +## New Branch
could you remove these lines? we don't want them in master

2024-08-27 11:07 UTC, alezana commented
@JoseLavariega @ysli16 still missing the docs update

2024-08-27 12:56 UTC, JoseLavariega commented
Docs markdown has been updated

2024-08-27 15:15 UTC, merged